### ISSUE TITLE
这个angular ueditor为什么上传本地图片老在loading，不显示呢

### ISSUE THREAD

**Issue by hxdyj** [dylike/meta.umeditor#3]
这个angular ueditor为什么上传本地图片老在loading，不显示呢

**Comment by dylike** [comment]
上传图片等功能需要配置好 UMEditor 的 serverUrl config，
![image](https://cloud.githubusercontent.com/assets/5422888/23204076/134df48a-f920-11e6-9cac-40f57100622c.png)
具体请参考[UMEditor Doc](http://fex.baidu.com/ueditor/#start-config)

**Comment by hxdyj** [comment]
那我如何隐藏本地上传那个项呢，只保留网络插入图片

这个我自己改image.js改好了

**Comment by hxdyj** [comment]
这个插件没有topbar没有code代码这项吗？ 

可以插入 代码吗？

**Comment by dylike** [comment]
[http://dylike.github.io/meta.umeditor/](http://dylike.github.io/meta.umeditor/) 这里是简单的DEMO，
此项目是对于UMEditor的ng指令封装，所以绝大部分UMEditor支持的功能都有的
你指的是toolbars中的【html】功能么？如果是这个那么UMEditor是提供的

**Comment by dylike** [comment]
如果你是希望在富文本中写代码的话，基础的UMEditor是不支持，需要额外的插件。
一般如果需要写代码（比如博客中的代码片段）用Markdown会比较好！
